spring.application.name=taxibooking
server.port=8081

spring.profiles.active=${ENV:dev}

#spring.profiles.active=prod



spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# upload image validation
spring.servlet.multipart.max-file-size=10MB